version: 0.2
phases:
  post_build:
    commands:
      - aws cloudformation deploy --template-file packaged-template.yaml --stack-name ${APP_STACK_NAME} --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
