version: 0.2
phases:
  build:
    commands:
      - cd sam-app
      # - sam build
      - aws cloudformation package --template-file template.yaml --s3-bucket ${SAM_BUCKET} --output-template-file packaged-template.yaml
  post_build:
    commands:
      - aws cloudformation deploy --template-file packaged-template.yaml --stack-name ${APP_STACK_NAME} --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset

# artifacts:
#   type: zip
#   files:
#     - packaged-template.yaml
