version: 0.2
phases:
  build:
    commands:
      - cd sam-app
      # - sam build
      - sam package --s3-bucket ${SAM_BUCKET} --output-template-file packaged-template.yaml

artifacts:
  type: zip
  files:
    - packaged-template.yaml
