version: 0.2
phases:
  deploy:
    commands:
      - cd sam-app
      # - sam deploy --guided
      - sam deploy --template-file packaged-template.yaml --stack-name ${APP_STACK_NAME} --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
