---
AWSTemplateFormatVersion: "2010-09-09"
Description:

Parameters:
  ProductionAccountId:
    Description: AWS account ID for development account
    Type: String
    AllowedPattern: (\d{12}|^$)
    ConstraintDescription: Must be an AWS account ID
    Default: '764573172366'
  TemplateBucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Default: mm-stack
    Description: S3 bucket name for stack templates
    Type: String
  TemplateKeyPrefix:
    Description: S3 bucket prefix for stack templates
    Default: templates
    Type: String
  GitHubOwner:
    Description: Github Owner
    Type: String
    Default:
  GitHubToken:
    Type: String
    Description: Person token for Git Repo
    Default:
  SecretToken:
    Type: String
    Description: Webhook authenticate token invoked by GitHub
    Default: 
  RepositoryName:
    Description: Git Repository
    Type: String
    # AllowedPattern:
    # ConstraintDescription:
    Default:
  BranchName:
    Description: Branch name of Git Repo
    Type: String
    # AllowedPattern:
    # ConstraintDescription:
    Default: master
  BuildImageName:
    Description: Image for application build
    Type: String
    Default: aws/codebuild/nodejs:10.1.0

Resources:

  UserStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductionAccountId: !Ref ProductionAccountId
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateKeyPrefix}/user.template.yaml
      TimeoutInMinutes: 60

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PipelineServiceRoleArn: !GetAtt UserStack.Outputs.PipelineServiceRoleArn
        ArtifactBucket: !GetAtt UserStack.Outputs.ArtifactBucket
        GitHubOwner: !Ref GitHubOwner
        GitHubToken: !Ref GitHubToken
        SecretToken: !Ref SecretToken
        RepositoryName: !Ref RepositoryName
        BranchName: !Ref BranchName
        BuildImageName: !Ref BuildImageName
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateKeyPrefix}/pipeline.template.yaml
      TimeoutInMinutes: 60
